grpc-js: Refactor code to eliminate runtime dependency cycles
grpc/grpc-node pull request #1829
Opened 2021-06-24 16:52 UTC by murgatroid99

The main changes here are moving the `ConnectivityState` enum and `SubchannelAddress` type (plus related definitions) into separate files so that other files can use them without importing `channel.ts` and `subchannel.ts` respectively. The load balancer registry code also makes the default configurable instead of hardcoding it as pick_first, to avoid a dependency cycle between that code and the pick_first code.

2021-06-24 19:05 UTC, merlinnot commented
Thank you for such a quick resolution, helps a lot!

2021-06-28 21:30 UTC, nicolasnoble requested changes
There's quite a few places where you've used double quotes for strings instead of simple quotes, (during imports that is), but aside from this, lgtm.

2021-06-28 21:42 UTC, murgatroid99 commented
Those double quotes were definitely added by VSCode's automatic refactoring functionality (which is otherwise very convenient).

2021-06-28 21:45 UTC, murgatroid99 commented
I think that the simplest way to handle that will be to just merge this as-is and then do a full reformatting as a separate PR.

2021-06-28 21:56 UTC, nicolasnoble approved these changes

2021-06-29 16:55 UTC, merged